# Generated by Django 5.2.13 on 2026-05-12 01:11
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoutingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("recommendation", models.TextField()),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("position_fit", models.TextField()),
                ("potential_rating", models.IntegerField(blank=True, null=True)),
                ("ready_for_first_team", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scouting_reports",
                        to="players.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scouting_reports",
                        to="players.player",
                    ),
                ),
                (
                    "scout",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scouting_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scouting_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shortlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlists",
                        to="players.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "scouting_shortlist",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_a",
                        to="players.player",
                    ),
                ),
                (
                    "player_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparisons_as_b",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "scouting_player_comparison",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player_a"], name="scouting_pl_player__fa0d93_idx"
                    ),
                    models.Index(
                        fields=["player_b"], name="scouting_pl_player__6f5ee3_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("player_a", models.F("player_b")), _negated=True
                        ),
                        name="prevent_same_player_comparison",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("reason", models.TextField()),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("model_version", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="players.player",
                    ),
                ),
                (
                    "recommended_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_recommendations",
                        to="players.club",
                    ),
                ),
            ],
            options={
                "db_table": "scouting_recommendation",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player"], name="scouting_re_player__e3d5cc_idx"
                    ),
                    models.Index(
                        fields=["recommended_club"],
                        name="scouting_re_recomme_840924_idx",
                    ),
                    models.Index(fields=["score"], name="scouting_re_score_b02178_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "recommended_club"),
                        name="unique_player_club_recommendation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShortlistPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlists",
                        to="players.player",
                    ),
                ),
                (
                    "shortlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="scouting.shortlist",
                    ),
                ),
            ],
            options={
                "db_table": "scouting_shortlist_player",
                "indexes": [
                    models.Index(
                        fields=["shortlist"], name="scouting_sh_shortli_ea4161_idx"
                    ),
                    models.Index(
                        fields=["player"], name="scouting_sh_player__4ed769_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shortlist", "player"), name="unique_shortlist_player"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("transfer_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("negotiating", "Negotiating"),
                            ("agreed", "Agreed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("loan", "Loan"),
                            ("free", "Free Transfer"),
                            ("return_loan", "Return Loan"),
                        ],
                        default="permanent",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="players.club",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="players.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="players.season",
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="players.club",
                    ),
                ),
            ],
            options={
                "db_table": "scouting_transfer",
                "ordering": ["-transfer_date"],
                "indexes": [
                    models.Index(
                        fields=["player"], name="scouting_tr_player__657d6a_idx"
                    ),
                    models.Index(
                        fields=["transfer_date"], name="scouting_tr_transfe_f2bae9_idx"
                    ),
                    models.Index(
                        fields=["to_club"], name="scouting_tr_to_club_20a27c_idx"
                    ),
                    models.Index(
                        fields=["from_club"], name="scouting_tr_from_cl_8cb5c9_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_club", models.F("to_club")), _negated=True
                        ),
                        name="prevent_same_transfer_club",
                    ),
                    models.UniqueConstraint(
                        fields=("player", "from_club", "to_club", "transfer_date"),
                        name="unique_transfer_record",
                    ),
                ],
            },
        ),
    ]
