# Generated by Django 6.0.4 on 2026-04-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='yolov8s', max_length=20)),
                ('confidence_threshold', models.FloatField(default=0.5)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=10)),
                ('total_objects_found', models.PositiveSmallIntegerField(default=0)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vision_detection_run',
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_class', models.CharField(choices=[('player', 'Jugador'), ('face', 'Rostro'), ('ball', 'Balón'), ('jersey', 'Camiseta'), ('text_region', 'Texto'), ('other', 'Otro')], max_length=20)),
                ('confidence', models.FloatField()),
                ('bbox_x', models.FloatField()),
                ('bbox_y', models.FloatField()),
                ('bbox_width', models.FloatField()),
                ('bbox_height', models.FloatField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
                ('detection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='vision.detectionrun')),
            ],
            options={
                'db_table': 'vision_detected_object',
            },
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vision/uploads/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento')], max_length=10)),
                ('source_type', models.CharField(choices=[('sticker', 'Cromo'), ('press_photo', 'Foto prensa'), ('match_video', 'Video partido'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vision_media_upload',
            },
        ),
        migrations.AddField(
            model_name='detectionrun',
            name='media_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.mediaupload'),
        ),
        migrations.CreateModel(
            name='OCRExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('player_name', 'Nombre'), ('jersey_number', 'Número'), ('club_name', 'Club'), ('position', 'Posición'), ('birth_date', 'Fecha nac.'), ('market_value', 'Valor'), ('other', 'Otro')], max_length=20)),
                ('raw_text', models.TextField()),
                ('normalized_text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision.detectionrun')),
                ('media_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.mediaupload')),
            ],
            options={
                'db_table': 'vision_ocr_extraction',
            },
        ),
    ]
