# Generated by Django 5.2.13 on 2026-05-12 01:11
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.FileField(upload_to="vision/uploads/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Imagen"),
                            ("video", "Video"),
                            ("document", "Documento"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sticker", "Cromo"),
                            ("press_photo", "Foto prensa"),
                            ("match_video", "Video partido"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vision_media_upload",
            },
        ),
        migrations.CreateModel(
            name="FaceMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_matches",
                        to="players.player",
                    ),
                ),
                (
                    "media_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_matches",
                        to="vision.mediaupload",
                    ),
                ),
            ],
            options={
                "db_table": "vision_face_match",
                "ordering": ["-similarity_score"],
            },
        ),
        migrations.CreateModel(
            name="DetectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_version", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("total_objects_found", models.PositiveSmallIntegerField(default=0)),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_runs",
                        to="vision.mediaupload",
                    ),
                ),
            ],
            options={
                "db_table": "vision_detection_run",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="OCRExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("player_name", "Nombre"),
                            ("jersey_number", "Número"),
                            ("club_name", "Club"),
                            ("position", "Posición"),
                            ("birth_date", "Fecha nac."),
                            ("market_value", "Valor"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("extracted_text", models.TextField()),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_extractions",
                        to="vision.mediaupload",
                    ),
                ),
            ],
            options={
                "db_table": "vision_ocr_extraction",
            },
        ),
        migrations.CreateModel(
            name="VisualReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_data", models.JSONField()),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visual_reports",
                        to="vision.mediaupload",
                    ),
                ),
            ],
            options={
                "db_table": "vision_visual_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_class",
                    models.CharField(
                        choices=[
                            ("player", "Jugador"),
                            ("face", "Rostro"),
                            ("ball", "Balón"),
                            ("jersey", "Camiseta"),
                            ("text_region", "Texto"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                ("bbox_x", models.PositiveIntegerField()),
                ("bbox_y", models.PositiveIntegerField()),
                ("bbox_width", models.PositiveIntegerField()),
                ("bbox_height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detected_objects",
                        to="players.player",
                    ),
                ),
                (
                    "detection_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_objects",
                        to="vision.detectionrun",
                    ),
                ),
            ],
            options={
                "db_table": "vision_detected_object",
                "indexes": [
                    models.Index(
                        fields=["detected_class"], name="vision_dete_detecte_fef38c_idx"
                    ),
                    models.Index(
                        fields=["confidence"], name="vision_dete_confide_2bf4ee_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0), ("confidence__lte", 1)
                        ),
                        name="detected_object_confidence_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("bbox_width__gt", 0), ("bbox_height__gt", 0)
                        ),
                        name="detected_object_positive_bbox",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mediaupload",
            index=models.Index(
                fields=["media_type"], name="vision_medi_media_t_688f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaupload",
            index=models.Index(
                fields=["source_type"], name="vision_medi_source__6a256c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mediaupload",
            index=models.Index(
                fields=["uploaded_at"], name="vision_medi_uploade_ac08f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facematch",
            index=models.Index(
                fields=["similarity_score"], name="vision_face_similar_0c11f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facematch",
            index=models.Index(
                fields=["player"], name="vision_face_player__831774_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="facematch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("similarity_score__gte", 0), ("similarity_score__lte", 1)
                ),
                name="face_match_similarity_range",
            ),
        ),
        migrations.AddIndex(
            model_name="detectionrun",
            index=models.Index(fields=["status"], name="vision_dete_status_d9b772_idx"),
        ),
        migrations.AddIndex(
            model_name="detectionrun",
            index=models.Index(
                fields=["processed_at"], name="vision_dete_process_ebb9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocrextraction",
            index=models.Index(
                fields=["field_type"], name="vision_ocr__field_t_a186ae_idx"
            ),
        ),
    ]
