# Generated by Django 5.2.13 on 2026-05-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_key', models.CharField(max_length=100, unique=True)),
                ('club_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dw_dimension_club',
            },
        ),
        migrations.CreateModel(
            name='DimensionCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_key', models.CharField(max_length=100, unique=True)),
                ('competition_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dw_dimension_competition',
            },
        ),
        migrations.CreateModel(
            name='DimensionPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=100, unique=True)),
                ('player_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dw_dimension_player',
            },
        ),
        migrations.CreateModel(
            name='DimensionSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_key', models.CharField(max_length=100, unique=True)),
                ('season_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dw_dimension_season',
            },
        ),
        migrations.CreateModel(
            name='FinancialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=18)),
                ('rule_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_financial_rule',
            },
        ),
        migrations.CreateModel(
            name='ClubFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=18)),
                ('wage_bill', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.season')),
            ],
            options={
                'db_table': 'analytics_club_financial',
            },
        ),
        migrations.CreateModel(
            name='FactDetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_key', models.CharField(max_length=100)),
                ('detections', models.IntegerField()),
                ('avg_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('model_version', models.CharField(max_length=100)),
                ('processing_time_ms', models.IntegerField()),
                ('detected_players', models.IntegerField()),
                ('season_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dw_fact_detection_run',
                'indexes': [models.Index(fields=['media_key'], name='dw_fact_det_media_k_1b240e_idx'), models.Index(fields=['season_key'], name='dw_fact_det_season__31cc74_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactFinancialCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_key', models.CharField(max_length=100)),
                ('rule_key', models.CharField(max_length=100)),
                ('passed', models.BooleanField()),
                ('checked_at', models.DateTimeField()),
                ('season_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dw_fact_financial_check',
                'indexes': [models.Index(fields=['club_key'], name='dw_fact_fin_club_ke_69e47e_idx'), models.Index(fields=['rule_key'], name='dw_fact_fin_rule_ke_26ea67_idx'), models.Index(fields=['season_key'], name='dw_fact_fin_season__d4dd4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactMarketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=100)),
                ('season_key', models.CharField(max_length=100)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dw_fact_market_value',
                'indexes': [models.Index(fields=['player_key'], name='dw_fact_mar_player__681247_idx'), models.Index(fields=['season_key'], name='dw_fact_mar_season__5d591f_idx'), models.Index(fields=['player_key', 'season_key'], name='dw_fact_mar_player__941e59_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=100)),
                ('season_key', models.CharField(max_length=100)),
                ('competition_key', models.CharField(max_length=100)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dw_fact_player_stat',
                'indexes': [models.Index(fields=['player_key'], name='dw_fact_pla_player__ffda9e_idx'), models.Index(fields=['season_key'], name='dw_fact_pla_season__a5102d_idx'), models.Index(fields=['competition_key'], name='dw_fact_pla_competi_4c6275_idx'), models.Index(fields=['player_key', 'season_key'], name='dw_fact_pla_player__f5da13_idx')],
            },
        ),
        migrations.CreateModel(
            name='FactTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_key', models.CharField(max_length=100)),
                ('from_club_key', models.CharField(blank=True, max_length=100, null=True)),
                ('to_club_key', models.CharField(max_length=100)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('transfer_date', models.DateField()),
                ('season_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dw_fact_transfer',
                'indexes': [models.Index(fields=['player_key'], name='dw_fact_tra_player__dde4a0_idx'), models.Index(fields=['from_club_key'], name='dw_fact_tra_from_cl_6ab0c9_idx'), models.Index(fields=['to_club_key'], name='dw_fact_tra_to_club_8c7fdf_idx'), models.Index(fields=['season_key'], name='dw_fact_tra_season__71ad61_idx'), models.Index(fields=['transfer_date'], name='dw_fact_tra_transfe_2d71ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('club_financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.clubfinancial')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialrule')),
            ],
            options={
                'db_table': 'analytics_financial_check',
            },
        ),
        migrations.CreateModel(
            name='SquadRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.season')),
            ],
            options={
                'db_table': 'analytics_squad_registration',
            },
        ),
        migrations.AddConstraint(
            model_name='clubfinancial',
            constraint=models.UniqueConstraint(fields=('club', 'season'), name='unique_club_season_financial'),
        ),
        migrations.AddConstraint(
            model_name='squadregistration',
            constraint=models.UniqueConstraint(fields=('club', 'player', 'season'), name='unique_squad_registration'),
        ),
    ]
