# Generated by Django 5.2.13 on 2026-04-14 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('ffp', 'Fair Play Financiero'), ('laliga_salary_cap', 'Tope salarial LaLiga'), ('squad_registration', 'Inscripción'), ('other', 'Otra')], max_length=30)),
                ('description', models.TextField()),
                ('threshold_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('threshold_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_financial_rule',
            },
        ),
        migrations.CreateModel(
            name='FinancialCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'Cumple'), ('fail', 'No cumple'), ('warning', 'Advertencia'), ('pending', 'Pendiente')], default='pending', max_length=10)),
                ('value_checked', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('threshold_applied', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.club')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.season')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.financialrule')),
            ],
            options={
                'db_table': 'analytics_financial_check',
            },
        ),
        migrations.CreateModel(
            name='ClubFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('wage_bill_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('transfer_income_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('transfer_expenditure_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('net_debt_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('wage_to_revenue_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.season')),
            ],
            options={
                'db_table': 'analytics_club_financial',
                'unique_together': {('club', 'season')},
            },
        ),
    ]
