# Generated by Django 5.2.13 on 2026-05-12 01:11

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'regulations_agent',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulations_embedding_cache',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('terminated', 'Rescindido'), ('pending', 'Pendiente')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=14)),
                ('salary_currency', models.CharField(default='EUR', max_length=3)),
                ('release_clause', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='regulations.agent')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='players.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='players.player')),
            ],
            options={
                'db_table': 'regulations_contract',
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(choices=[('salary', 'Salary'), ('release', 'Release Clause'), ('bonus', 'Bonus'), ('duration', 'Duration'), ('image_rights', 'Image Rights'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='regulations.contract')),
            ],
            options={
                'db_table': 'regulations_contract_clause',
            },
        ),
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulations_legal_query',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('model_used', models.CharField(default='rag', max_length=100)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('chunks_used', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='regulations.legalquery')),
            ],
            options={
                'db_table': 'regulations_legal_answer',
            },
        ),
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(choices=[('fifa_regulation', 'FIFA'), ('laliga_regulation', 'LaLiga'), ('financial', 'Financiero'), ('law', 'Ley'), ('other', 'Otro')], max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='es', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='regulations/')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_regulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulations_document',
            },
        ),
        migrations.CreateModel(
            name='RegulationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('clause_type', models.CharField(blank=True, max_length=100)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('embedding_model', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', max_length=100)),
                ('is_useful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='regulations.regulationdocument')),
            ],
            options={
                'db_table': 'regulations_chunk',
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=255)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('source_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='regulations.legalanswer')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulations.regulationchunk')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulations.regulationdocument')),
            ],
            options={
                'db_table': 'regulations_legal_source',
                'ordering': ['-relevance_score'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='regulations_status_eb9d87_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['end_date'], name='regulations_end_dat_9009ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['player'], name='regulations_player__ab5fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['club'], name='regulations_club_id_420a29_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('player',), name='unique_active_contract_per_player'),
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['contract'], name='regulations_contrac_435895_idx'),
        ),
        migrations.AddIndex(
            model_name='contractclause',
            index=models.Index(fields=['clause_type'], name='regulations_clause__ee1547_idx'),
        ),
        migrations.AddIndex(
            model_name='legalquery',
            index=models.Index(fields=['created_at'], name='regulations_created_fc2380_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationdocument',
            index=models.Index(fields=['doc_type'], name='regulations_doc_typ_df4ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationdocument',
            index=models.Index(fields=['category'], name='regulations_categor_72a7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationdocument',
            index=models.Index(fields=['is_active'], name='regulations_is_acti_23b902_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulationdocument',
            constraint=models.UniqueConstraint(fields=('title', 'version'), name='unique_document_version'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['document'], name='regulations_documen_f2f600_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['article_number'], name='regulations_article_c5b0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['clause_type'], name='regulations_clause__d3676f_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['page'], name='regulations_page_eeec4e_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['is_useful'], name='regulations_is_usef_5932c9_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='regulations_documen_061059_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['document', 'article_number'], name='regulations_documen_74b381_idx'),
        ),
        migrations.AddConstraint(
            model_name='regulationchunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'),
        ),
        migrations.AddIndex(
            model_name='legalsource',
            index=models.Index(fields=['answer'], name='regulations_answer__ca3b45_idx'),
        ),
        migrations.AddIndex(
            model_name='legalsource',
            index=models.Index(fields=['document'], name='regulations_documen_4c09a4_idx'),
        ),
        migrations.AddIndex(
            model_name='legalsource',
            index=models.Index(fields=['chunk'], name='regulations_chunk_i_902a42_idx'),
        ),
    ]
