# Generated by Django 5.2.13 on 2026-04-14 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('embedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulations_embedding_cache',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('expired', 'Expirado'), ('terminated', 'Rescindido'), ('pending', 'Pendiente')], default='active', max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('annual_salary_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='players.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='players.player')),
            ],
            options={
                'db_table': 'regulations_contract',
            },
        ),
        migrations.CreateModel(
            name='LegalQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'regulations_legal_query',
            },
        ),
        migrations.CreateModel(
            name='LegalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('model_used', models.CharField(default='gpt', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='regulations.legalquery')),
            ],
            options={
                'db_table': 'regulations_legal_answer',
            },
        ),
        migrations.CreateModel(
            name='RegulationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('fifa_regulation', 'FIFA'), ('laliga_regulation', 'LaLiga'), ('financial', 'Financiero'), ('law', 'Ley'), ('other', 'Otro')], max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='es', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='regulations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'regulations_document',
                'indexes': [models.Index(fields=['doc_type'], name='regulations_doc_typ_df4ac7_idx'), models.Index(fields=['category'], name='regulations_categor_72a7b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegulationChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('clause_type', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='regulations.regulationdocument')),
            ],
            options={
                'db_table': 'regulations_chunk',
            },
        ),
        migrations.CreateModel(
            name='LegalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField()),
                ('source_text', models.TextField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='regulations.legalanswer')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.regulationchunk')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regulations.regulationdocument')),
            ],
            options={
                'db_table': 'regulations_legal_source',
            },
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['document'], name='regulations_documen_f2f600_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['article_number'], name='regulations_article_c5b0aa_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['clause_type'], name='regulations_clause__d3676f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='regulationchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AlterUniqueTogether(
            name='legalsource',
            unique_together={('answer', 'chunk')},
        ),
    ]
