# Generated by Django 5.2.13 on 2026-04-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalsource',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regulations.regulationchunk'),
        ),
    ]
