# Generated by Django 5.2.13 on 2026-04-14 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_alter_legalsource_chunk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalsource',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='legalsource',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regulations.regulationdocument'),
        ),
    ]
