# Generated by Django 5.2.13 on 2026-04-21 03:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_alter_legalsource_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legalsource',
            name='doc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='legalsource',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regulationchunk',
            name='is_useful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regulationchunk',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalanswer',
            name='model_used',
            field=models.CharField(default='rag', max_length=100),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['page'], name='regulations_page_eeec4e_idx'),
        ),
    ]
