# Generated by Django 5.2.12 on 2026-05-09 16:13

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerclubhistory_seasonplayerstat_and_more'),
        ('regulations', '0004_legalsource_created_at_legalsource_doc_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='legalsource',
            options={'ordering': ['-relevance_score']},
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='embeddingcache',
            name='text_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='legalanswer',
            name='chunks_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulationdocument',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulationdocument',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='regulationdocument',
            name='total_chunks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='regulationdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='embeddingcache',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
        migrations.AlterField(
            model_name='embeddingcache',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legalanswer',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='regulations.legalquery'),
        ),
        migrations.AlterField(
            model_name='legalquery',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='legalsource',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulations.regulationchunk'),
        ),
        migrations.AlterField(
            model_name='legalsource',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulations.regulationdocument'),
        ),
        migrations.AlterField(
            model_name='regulationchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AlterField(
            model_name='regulationchunk',
            name='embedding_model',
            field=models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', max_length=100),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='regulations_status_eb9d87_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['date_end'], name='regulations_date_en_5bab63_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationchunk',
            index=models.Index(fields=['is_useful'], name='regulations_is_usef_5932c9_idx'),
        ),
        migrations.AddIndex(
            model_name='regulationdocument',
            index=models.Index(fields=['is_processed'], name='regulations_is_proc_24931b_idx'),
        ),
    ]
