# Generated by Django 5.2.13 on 2026-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
