# Generated by Django 5.2.13 on 2026-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_competition_external_id_competition_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
