# Generated by Django 5.2.12 on 2026-05-09 16:13

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerClubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('loan', models.BooleanField(default=False)),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'db_table': 'players_club_history',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='SeasonPlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.PositiveSmallIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'players_season_stat',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='face_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['status'], name='players_pla_status_6a7a33_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['position'], name='players_pla_positio_2502c1_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['current_club'], name='players_pla_current_41f105_idx'),
        ),
        migrations.AddField(
            model_name='playerclubhistory',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_history', to='players.club'),
        ),
        migrations.AddField(
            model_name='playerclubhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_history', to='players.player'),
        ),
        migrations.AddField(
            model_name='playerclubhistory',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.season'),
        ),
        migrations.AddField(
            model_name='seasonplayerstat',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.club'),
        ),
        migrations.AddField(
            model_name='seasonplayerstat',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.competition'),
        ),
        migrations.AddField(
            model_name='seasonplayerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.player'),
        ),
        migrations.AddField(
            model_name='seasonplayerstat',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='players.season'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonplayerstat',
            unique_together={('player', 'season', 'club', 'competition')},
        ),
    ]
