# Generated by Django 5.2.13 on 2026-05-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
