# Generated by Django 5.2.13 on 2026-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_competition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='iso_code',
        ),
        migrations.RemoveField(
            model_name='player',
            name='nationality',
        ),
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='club',
            name='national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='stadium_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='season_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='match',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playernationality',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='injury',
            name='injury_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('injured', 'Injured'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerclubhistory',
            name='transfer_fee',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='playerposition',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seasonplayerstat',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='suspension',
            name='matches_suspended',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['external_id'], name='players_mat_externa_39d1a1_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['full_name'], name='players_pla_full_na_c03349_idx'),
        ),
        migrations.AddConstraint(
            model_name='playernationality',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('player',), name='unique_primary_nationality_per_player'),
        ),
    ]
